version: "3.3"
services:
  tt1: # master
    image: tarantool/tarantool:latest
    volumes:
      - /Users/jamalabdulnasir/Go/golib/src/github.com/jamalanasier/ja_na/scripts/:/opt/tarantool/
    command: tarantool /opt/tarantool/dhands.lua
    environment:
      - TARANTOOL_USER_NAME=tester
      - TARANTOOL_USER_PASSWORD=tester
    ports:
      - 3303:3303
      
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000